### ISSUE TITLE
Remove trailing double equals on global ids?

### ISSUE THREAD

**Issue by jaydiablo** [ivome/graphql-relay-php#11]
What are your thoughts on removing the `==` from the global ids generated by graphql-relay-php?

PHP doesn't require them when base64 decoding: https://3v4l.org/VXkhW

I think it makes them look a lot nicer (saves a couple of bytes in request/responses too) to have the double equals removed.

**Comment by ivome** [comment]
In general I think the IDs without the padding look nicer. (I also implemented IDs in one projects like that)
If you are using a PHP only system this does not really matter. For javascript, this also is not an issue. But some projects might consume the data with other programming languages and might decode the IDs. 

Wikipedia says: 

> In theory, the padding character is not needed for decoding, since the number of missing bytes can be calculated from the number of Base64 digits. **In some implementations, the padding character is mandatory**, while for others it is not used. 

So I would keep them in this library in favor of compatibility. Especially since you can create custom ID encoder/decoder functions with a few lines of code and use them in your project along with all the other functionality in this library. 

Just my 2 cents 😄
